config/routes.rb
Rails.application.routes.draw do





  get '/', to: redirect('/ru')

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  #devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  scope ':locale' do

    resources :categories
    resources :instructions do
      member do
        put "like" => "instructions#upvote"
        put "dislike" => "instructions#downvote"
        put "unvote" => "instructions#unvote"
        get 'instructions/destroyimage/(:image_id)', to: 'instructions#destroyimage', as: 'destroyimage'
      end
    end

    resources :steps do
      resources :comments
    end

    resources :users
    post 'banned/:id', to: "users#banned", :as => :banned_user
    post 'manager/:id', to: "users#manager", :as => :manager_user


    devise_scope :user do
      get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
      get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
      get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth
      #get '/users/auth/:provider', to: "users/omniauth_callbacks#authorisate", as: :user_omniauth_authorize
      devise_for :users, skip: [:omniauth_callbacks]


    end

    get 'show', :to => 'home#show'

    root 'home#index'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instruction.rb
class Instruction < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :steps

  acts_as_votable

  accepts_nested_attributes_for :steps, allow_destroy: true
  validates :title, presence: true
  validates :body, presence: true
  validates :steps, :length => { :minimum => 1 }
  validates_associated :steps
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  before_action :set_instruction, only: [:show, :edit, :update, :destroy, :upvote, :downvote, :unvote]
  # GET /instructions
  # GET /instructions.json
  def index
    @instructions = Instruction.eager_load(:category).all.order(created_at: :desc)
  end

  # GET /instructions/1
  # GET /instructions/1.json
  def show
    @like = find_like
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "file_name",
               encoding: "utf-8",
               layout: "application.pdf.erb",
               disable_internal_links: false,
               disable_external_links: false,
               disable_links:          false,
               disable_toc_links:      false,
               disable_back_links:     false
      end
    end
  end

  def destroyimage
    Cloudinary::Uploader.destroy("#{params[:id]}")
    @index = params[:index]
  end

  # GET /instructions/new
  def new
    @instruction = Instruction.new
    authorize! :create, @instruction
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # GET /instructions/1/edit
  def edit
    authorize! :update, @instruction
    @categories = Category.all.map{|c| [ c.name, c.id ] }
    @index = 0
  end

  # POST /instructions
  # POST /instructions.json
  def create
    @instruction = Instruction.new(instruction_params)
    @categories = Category.all.map{|c| [ c.name, c.id ] }
    @instruction.category_id = params[:category_id]
    @instruction.user_id = current_user['id']
    respond_to do |format|
      if @instruction.save
        format.html { redirect_to @instruction, notice: 'Instruction was successfully created.' }
        format.json { render :show, status: :created, location: @instruction }
      else
        format.html { render :new }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructions/1
  # PATCH/PUT /instructions/1.json
  def update

    @categories = Category.all.map{|c| [ c.name, c.id ] }
    respond_to do |format|

      if @instruction.update(instruction_params)
        format.html { redirect_to @instruction, notice: 'Instruction was successfully updated.' }
        format.json { render :show, status: :ok, location: @instruction }
      else
        format.html { render :edit }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructions/1
  # DELETE /instructions/1.json
  def destroy
    authorize! :destroy, @instruction
    @instruction.destroy
    respond_to do |format|
      format.html { redirect_to instructions_url, notice: 'Instruction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @instruction.vote_up current_user
  end

  def downvote
    @instruction.vote_down current_user
  end

  def unvote
    @instruction.unvote_by current_user
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instruction
      @instruction = Instruction.eager_load(:category, steps: :comments).where(id: params[:id]).order('steps.index').to_a.first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instruction_params
      params.require(:instruction).permit(:title, :body, :category_id, :user_id, :youtube_url, steps_attributes: [:title, :body, :image, :_destroy, :id, :index])
    end

    def find_like

      if user_signed_in?
        buf = Votes.find_by(voter_id: current_user.id, votable_id: @instruction.id)
        buf == nil ? nil : buf.vote_flag
      else
        return nil
      end

    end

end

app/helpers/instructions_helper.rb
module InstructionsHelper
  def youtube_embded(youtube_url)
    youtube_id = youtube_url.split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}", width: '100%', height: '350px',  frameborder: 0)
  end

  def qr(url)
    RQRCode::QRCode.new( url, :size => 5, :level => :h )
  end

  def index(index)
    index.split("instruction[steps_attributes][").second[0...-1]
  end

  def image_publick_id(form)
    form =~  /value="(\w*)"/ ? form.scan( /value="(\w*)"/).last.first.to_s : ""
  end

  def display(image)
    "display:" + (image.to_s.empty? ? "block" : "none")
  end
end

app/views/instructions/_form.html.erb
<%= cloudinary_js_config %>
<%= form_for(instruction) do |f| %>
  <% if instruction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instruction.errors.count, "error") %> prohibited this instruction from being saved:</h2>

      <ul>
      <% instruction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label t(:title), class: "col-2 col-form-label" %>
    <div class="col-8">
      <%= f.text_field :title, class: "form-control", required: true %>
    </div>
  </div>
    <div class="form-group row">
      <%= f.label t(:category), class: "col-2 col-form-label" %>
      <div class="col-8">
        <%= select_tag(:category_id, options_for_select(@categories), class: "form-control") %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :youtube_url, class: "col-2 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :youtube_url, class: "form-control" %>
      </div>
    </div>


      <%= f.text_area :body, required: true %>

    <div class="row">
      <div id="sortable">



        <!-- Modal -->

      <%= f.nested_fields_for  :steps do |ff| %>
            <%= ff.hidden_field :index, value: index(ff.object_name), data: {order: "true" }  %>
            <div class="ui-state-default row step" data-toggle="modal" data-target="#step<%= index(ff.object_name) %>">
            <div class='col-2'>
            <h2><i class='fa fa-arrows-alt'></i><number><%= index(ff.object_name) %></number><%= t(:step) %></h2></div>
        <div class='col-10 title'>
        <p><%= index(ff.object_name) %> <%=  ff.remove_nested_fields_link do %><i class='fa fa-trash' aria-hidden='true'></i><% end %></p></div></div>






            <div class="modal fade" id="step<%= index(ff.object_name) %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-large" role="document">
                <div class="modal-content">
                  <div class="modal-body">
                    <div class="field">
                      <h5>Edit step</h5>
                      <div class="form-group row">
                        <%= ff.label t(:title), class: "col-2 col-form-label"  %>
                        <div class="col-8">
                          <%= ff.text_field :title, class: "form-control", required: true  %>
                        </div>
                      </div>
                      <div class="form-group row">
                        <%= ff.label t(:body), class: "col-2 col-form-label"  %>
                        <div class="col-8">
                        <%= ff.text_area :body, required: true, width: "100%" %>
                        </div>
                      </div>


                      <div class="form_line">
                        <% if image_publick_id(ff.text_field(:image)) != "" %>
                            <div id="prev<%= index(ff.object_name) %>" class="prev">
                              <%= cl_image_tag( image_publick_id(ff.text_field(:image)), :crop => :fill, :quality=>"auto:low", class: "img-thumbnail") %>
                              <%= link_to fa_icon('trash'), destroyimage_instruction_path(image_publick_id(ff.text_field(:image)), index: index(ff.object_name), id: instruction.id), remote: true %>
                            </div>
                        <% end %>
                            <div  id="direct_upload" style="<%= display(image_publick_id(ff.text_field(:image))) %>"  class="brd" ondrop="this.style.display='none'" ondragover="this.style.backgroundColor='#14998D'" ondragleave="this.style.backgroundColor='#fff'">
                              <div class="form_controls">
                                <%= ff.cl_image_upload(:image, :return_delete_token=>true) %>
                                <%= ff.hidden_field :image, class: "hidden_field" %>
                              </div>
                            </div>


                        <div class="progress">
                          <div class="progress-bar" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <div class="form_controls">
                          <div class="preview"></div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
      <% end %>
      </div>

    </div>
    <%= f.add_nested_fields_link :steps do %>

    <div class="brd">
      <%= fa_icon "plus" %>
      <%= t(:add_step) %>
    </div>
    <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instructions/_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-large" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <div class="owl-carousel owl-theme">
          <% steps.each_with_index do |step, index| %>
              <div class="item">
                <div class="row">
                  <div class="col-8">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel"><%= "#{index+1} #{t(:step).upcase}. #{step.title.capitalize}" %></h5>

                    </div>


                    <p><%= raw(step.body) %></p>
                    <p class="text-center"> <%= cl_image_tag( step.image, :crop => :fill, class: 'img-owl', :quality=>"auto:low") %></p>

                  </div>
                  <div class="col-4">
                    <div class="modal-header">

                      <h5><%= t :comments %></h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>

                    </div>
                    <div id="comments<%= step.id %>" class="comments">
                    <% step.comments.each do |comment| %>


                        <blockquote class="blockquote" id="blockquote<%= comment.id %>">
                          <p class="mb-0">
                            <%= comment.body %>
                            <% if can? :destroy, comment %>
                              <%= link_to fa_icon('trash'), step_comment_path(step_id: step.id, comment_id: comment.id), method: :delete, remote: true  %>
                            <% end %>
                          </p>
                          <footer class="blockquote-footer"><%= comment.user_id %> <cite title="Source Title"><small><%= I18n.localize(comment.created_at, format: :long) %></small></cite></footer>
                        </blockquote>
                    <% end %>
                    </div>
                    <% if user_signed_in? %>
                    <%= render 'comments/form', step: step %>
                    <% end %>
                  </div>
                </div>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/instructions/destroyimage.js.erb
$('#prev<%= @index %>').next().css('display','block');
$('#prev<%= @index %>').remove();
$('#instruction_steps_attributes_<%= @index %>_image').val("");

app/views/instructions/downvote.js.erb
if ($('#unlike').length) {
    $('like').html(` <%= link_to fa_icon("thumbs-o-up"), like_instruction_path(@instruction), method: :put, remote: true %> `)
}
$('dislike').html(`<%= link_to fa_icon("thumbs-down"), unvote_instruction_path(@instruction), method: :put, remote: true, id: "unlike" %>`);
$('rate').html(` <%= @instruction.cached_votes_score %> `);

app/views/instructions/edit.html.erb
<h1>Editing Instruction</h1>

<%= render 'form', instruction: @instruction %>

<%= link_to 'Show', @instruction %> |
<%= link_to 'Back', instructions_path %>

app/views/instructions/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t(:instructions) %></h1>

<table class="table">
  <thead>
    <tr>
      <th><%= t(:title) %></th>
      <th><%= t(:body) %></th>
      <th><%= t(:category) %></th>
      <th><%= t(:user) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructions.each do |instruction| %>
      <tr>
        <td><%= instruction.title %></td>
        <td><%= raw(instruction.body) %></td>
        <td><%= instruction.category.name %></td>
        <td><%= instruction.user_id %></td>
        <td><%= link_to t(:show), instruction, class: "btn btn-outline-success" %></td>
        <% if can? :edit, instruction %>
        <td><%= link_to t(:edit), edit_instruction_path(instruction), class: "btn btn-outline-warning" %></td>
        <% end %>
        <% if can? :destroy, instruction %>
        <td><%= link_to t(:destroy), instruction, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Instruction.new  %>
<%= link_to t(:new_instructions), new_instruction_path, class: "btn btn-outline-primary" %>
<% end %>

app/views/instructions/new.html.erb
<h1>New Instruction</h1>
<div class="container">
<%= render 'form', instruction: @instruction %>





<%= link_to 'Back', instructions_path %>



<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

</div>

app/views/instructions/show.html.erb
<h1 class="display-4"><%= @instruction.title %></h1>


<p>
  <strong><%= t(:category) %>:</strong>
  <%= @instruction.category.name %>,
  <strong><%= t(:user) %>:</strong>
  <%= @instruction.user_id %>,
  <strong>Pdf:</strong>
  <%= link_to fa_icon('file-pdf-o'), instruction_path(@instruction, :format => :pdf)  %>,


  <strong><%= t(:rating) %>: </strong>
  <% if user_signed_in? %>
  <dislike>

    <% if @like == false %>
        <%= link_to fa_icon("thumbs-down"), unvote_instruction_path(@instruction), method: :put, remote: true, id: "unlike" %>
    <% else %>
        <%= link_to fa_icon("thumbs-o-down"), dislike_instruction_path(@instruction), method: :put, remote: true %>
    <% end %>
  </dislike>
  <% end %>
  <rate><%= @instruction.cached_votes_score %></rate>
  <% if user_signed_in? %>
  <like>
  <% if @like == true %>
      <%= link_to fa_icon("thumbs-up"), unvote_instruction_path(@instruction), method: :put, remote: true, id: "unlike" %>
  <% else %>
      <%= link_to fa_icon("thumbs-o-up"), like_instruction_path(@instruction), method: :put, remote: true %>
  <% end %>
  </like>
  <% end %>

</p>

<div class="lead">
  <%= raw(@instruction.body) %>
</div>

<% if @instruction.youtube_url %>
<p>
  <div class="row">
    <div class="col-9">
      <%= youtube_embded(@instruction.youtube_url) if @instruction.youtube_url %>
    </div>
    <div class="col-3">
      <%= raw qr(@instruction.youtube_url).as_svg(offset: 0, color: '000',
          shape_rendering: 'crispEdges',
          module_size: 4) %>
    </div>
  </div>
</p>
<% end %>

<p class="lead">Как всё-таки это сделать?</p>


<div class="container">
  <% @instruction.steps.each_with_index do |step, index| %>

  <div class="row step" style="background-image: url(<%=cloudinary_url(step.image) %>)" onclick="goStep(<%= index %>)">
    <div class="col-2">
    <h2><%= "#{index+1} #{t(:step).upcase}" %></h2>
    </div>
    <div class="col-10 title">
    <p> <%= step.title.upcase %></p>
    </div>

  </div>


  <% end %>
</div>
<%= render 'modal', steps: @instruction.steps %>
<% if can? :update, @instruction %>
<%= link_to 'Edit', edit_instruction_path(@instruction) %>
<% end %>
<%= link_to 'Back', instructions_path %>

app/views/instructions/show.pdf.erb
<h1><%= @instruction.title %></h1>


<p>
  <strong><%= t(:category) %>:</strong>
  <%= @instruction.category.name %>,
  <strong><%= t(:user) %>:</strong>
  <%= @instruction.user_id %>
</p>

<div class="lead">
  <%= raw(@instruction.body) %>
</div>

<% if @instruction.youtube_url %>
    <p>
    <div class="row">
      <div class="col-5">
        <%= raw qr(@instruction.youtube_url).as_svg(offset: 0, color: '000',
                                                    shape_rendering: 'crispEdges',
                                                    module_size: 4) %>
      </div>
      <div class="col-3">
        <h4>YouTube</h4>
      </div>
    </div>
    </p>
<% end %>

<p class="lead">Как всё-таки это сделать?</p>

<div class="container">
  <% @instruction.steps.each_with_index do |step, index| %>

          <div class="row step">
            <div class="col-2">
              <h2><%= "#{index+1} #{t(:step).upcase}" %></h2>
            </div>
            <div class="col-10 title">
              <p> <%= step.title.upcase %></p>
            </div>
          </div>
          <p>
            <%= raw(step.body) %>
          </p>
          <%= image_tag cloudinary_url(step.image), width: "100%" %>


  <% end %>
</div>

app/views/instructions/unvote.js.erb
if ($("#unlike").parent()[0].tagName == 'LIKE'){
    $('like').html(` <%= link_to fa_icon("thumbs-o-up"), like_instruction_path(@instruction), method: :put, remote: true %> `)
    $('rate').html(` <%= @instruction.cached_votes_score %> `)
}
else{
    $('dislike').html(` <%= link_to fa_icon("thumbs-o-down"), dislike_instruction_path(@instruction), method: :put, remote: true %> `)
    $('rate').html(` <%= @instruction.cached_votes_score %> `)
}

app/views/instructions/upvote.js.erb
if ($('#unlike').length) {
    $('dislike').html(` <%= link_to fa_icon("thumbs-o-down"), dislike_instruction_path(@instruction), method: :put, remote: true %> `)
}
$('like').html(`<%= link_to fa_icon("thumbs-up"), unvote_instruction_path(@instruction), method: :put, remote: true, id: "unlike" %>`);
$('rate').html(` <%= @instruction.cached_votes_score %> `);