config/routes.rb
Rails.application.routes.draw do





  get '/', to: redirect('/ru')

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  #devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  scope ':locale' do

    resources :categories
    resources :instructions do
      member do
        put "like" => "instructions#upvote"
        put "dislike" => "instructions#downvote"
        put "unvote" => "instructions#unvote"
        get 'instructions/destroyimage/(:image_id)', to: 'instructions#destroyimage', as: 'destroyimage'
      end
    end

    resources :steps do
      resources :comments
    end

    resources :users
    post 'banned/:id', to: "users#banned", :as => :banned_user
    post 'manager/:id', to: "users#manager", :as => :manager_user


    devise_scope :user do
      get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
      get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
      get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth
      #get '/users/auth/:provider', to: "users/omniauth_callbacks#authorisate", as: :user_omniauth_authorize
      devise_for :users, skip: [:omniauth_callbacks]


    end

    get 'show', :to => 'home#show'

    root 'home#index'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded fixed-top ">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to image_tag("logo.png"), root_path, class: 'navbar-brand logo' %>
  <div class="collapse navbar-collapse nav-mg" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= li_link_to t(:home), root_path, class: 'nav-link', 'li-class' => 'nav-item' %>
      <%= li_link_to t(:users), users_path, class: 'nav-link', 'li-class' => 'nav-item' %>
      <%= li_link_to t(:categories), categories_path, class: 'nav-link', 'li-class' => 'nav-item' %>
      <%= li_link_to t(:instructions), instructions_path, class: 'nav-link', 'li-class' => 'nav-item' %>
    </ul>
    <ul class="navbar-nav mr-right">
    <% if user_signed_in?%>
          <li class="nav-item dropdown">
            <%= link_to image_tag(current_user.image, alt: current_user.name, size: "40x40", class: 'img-rounded' )+
                            current_user.name, '#', class: 'nav-blink nav-link dropdown-toggle',
                        id: 'navbarDropdownMenuLink', 'data-toggle' => "dropdown",
                        'aria-haspopup' => "true", 'aria-expanded' => "false"%>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to t(:logout), destroy_user_session_path, class: 'dropdown-item'  %>
            </div>
          </li>
    <% else %>
          <span class="navbar-text"><%= t :loginwith %></span>
          <%= link_to fa_icon('facebook-official'), localized_omniauth_path(:facebook, :origin=>request.path), class: 'nav-link'  %>
          <%= link_to fa_icon('twitter'), localized_omniauth_path(:twitter, :origin=>request.path), class: 'nav-link'  %>
          <%= link_to fa_icon('vk'), localized_omniauth_path(:vkontakte, :origin=>request.path), class: 'nav-link'  %>
    <% end %>
      <% I18n.available_locales.each do |locale| %>
          <li class="nav-item lang">
            <%= link_to_unless_current t("languages.#{locale.to_s}"), {locale: locale}, class: 'link-gr nav-link'%>
          </li>
      <% end %>
    </ul>
  </div>
</nav>
<% flash.each do |message_type, message| %>
  <div class="container">
    <div class="alert alert-<%= message_type %> alert-dismissible fade show margin-15" role="alert">
      <%= message %>
    </div>
  </div>
<% end %>
<script type="text/javascript">
    I18n.locale = '<%= I18n.locale %>';
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= params[:locale] %>">
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= render 'layouts/shim' %>
  </head>
  <body class="body-mt">
  <%= render 'layouts/header' %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.pdf.erb
<!doctype html>
<html>
<head>
  <meta charset="UTF-8" />
  <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
  <%= wicked_pdf_javascript_include_tag "number_pages" %>
</head>
<body onload='number_pages'>
<div id="header">
  <%= wicked_pdf_image_tag 'logo-pdf.png'%>
  <%= link_to t(:home), root_url %>
</div>
<div id="content">
  <%= yield %>
</div>

</body>
</html>